-- Complaint Priority SQL QUERY
SELECT C.COMPLAINT_PK,
       C.COMPLAINT_ID,
       C.COMPLAINT_DESC,
       C.COMPLAINT_DATE,
       C.COMPLAINT_TYPE,
       C.COMPLAINT_STATUS,
       C.COMPLAINT_REG_OWNER_NAME 
FROM COM_REG C;