INSERT INTO SYUSR_PUBLIC(
   USRID,
   USRNAME,
   STUDENT_department,
   STUDENT_SAMESTER,
   STUDENT_SECTION,
   PASSWORD
) 
VALUES(
   :P7_USRID,
   :P7_USRNAME,
   :P7_STUDENT_department,
   :P7_STUDENT_SAMESTER,
   :P7_STUDENT_SECTION,
   :P7_PASSWORD
);