UPDATE SYUSR_PUBLIC
SET SYUSR_PK = :P7_SYUSR_PK,
    USRID = :P7_USRID,
    USRNAME = :P7_USRNAME,
    STUDENT_department = :P7_STUDENT_department,
    STUDENT_SAMESTER = :P7_STUDENT_SAMESTER,
    STUDENT_SECTION = :P7_STUDENT_SECTION,
    RIGHT_USER = :P7_RIGHT_USER
WHERE SYUSR_PK = :P7_SYUSR_PK;