-- Complaint Register SQL QUERY 
SELECT C.COMPLAINT_PK,
       C.COMPLAINT_ID,
       C.COMPLAINT_DESC,
       C.COMPLAINT_DATE,
       C.COMPLAINT_TYPE,
       C.COMPLAINT_STATUS
FROM COM_REG C
WHERE STUDENT_ID = :GS_USRID 
OR :GS_USER_ROLE = 'Y'
ORDER BY C.COMPLAINT_ID;

-- System Users SQL QUERY
SELECT SYUSR_PK, 
       USRID, 
       USRNAME
FROM SYUSR_PUBLIC;