-- SYUSR_PUBLIC
CREATE OR REPLACE TRIGGER trg_generate_SYUSR_PK
BEFORE INSERT OR UPDATE ON SYUSR
FOR EACH ROW
BEGIN
  IF :NEW.SYUSR_PK IS NULL THEN
    SELECT SQ_SYUSR_PK.NEXTVAL INTO :NEW.SYUSR_PK FROM DUAL;
  END IF;
END;

-- COM_REG
CREATE OR REPLACE TRIGGER trg_generate_complaint_pk
BEFORE INSERT ON COM_REG
FOR EACH ROW
BEGIN
  IF :NEW.COMPLAINT_PK IS NULL THEN
    SELECT SEQ_COMPLAINT_PK.NEXTVAL INTO :NEW.COMPLAINT_PK FROM DUAL;
  END IF;
END;

CREATE OR REPLACE TRIGGER trg_generate_complaint_id
BEFORE INSERT ON COM_REG
FOR EACH ROW
BEGIN
   SELECT seq_complaint_id.nextval INTO :NEW.COMPLAINT_ID FROM DUAL;
END;