-- SYUSR_PUBLIC TABLE
CREATE TABLE SYUSR_PUBLIC(	
	SYUSR_PK NUMBER(*,0) NOT NULL ENABLE, 
	USRID VARCHAR2(30) NOT NULL ENABLE, 
	USRNAME VARCHAR2(50) NOT NULL ENABLE, 
	PASSWORD VARCHAR2(50), 
	STUDENT_DEPARTMENT VARCHAR2(150), 
	STUDENT_SAMESTER VARCHAR2(150), 
	STUDENT_SECTION VARCHAR2(150), 
	RIGHT_USER VARCHAR2(15), 
	PRIMARY KEY (SYUSR_PK),
    USING INDEX ENABLE
);

-- COM_REG TABLE
CREATE TABLE COM_REG (	
	COMPLAINT_PK NUMBER(*,0), 
    COMPLAINT_ID NUMBER, 
	COMPLAINT_DESC VARCHAR2(100) NOT NULL ENABLE, 
	COMPLAINT_DATE TIMESTAMP (6) NOT NULL ENABLE, 
	COMPLAINT_TYPE VARCHAR2(50) NOT NULL ENABLE, 
	COMPLAINT_STATUS VARCHAR2(50), 
	COMPLAINT_REG_OWNER_NAME VARCHAR2(250), 
	REMARKS VARCHAR2(200), 
	STUDENT_ID VARCHAR2(60), 
	STUDENT_NAME VARCHAR2(260), 
	STUDENT_DEPARTMENT VARCHAR2(250), 
	STUDENT_SAMESTER VARCHAR2(250), 
	STUDENT_SECTION VARCHAR2(250), 
	STUDENT_REMARKS VARCHAR2(250), 
	PRIMARY KEY (COMPLAINT_PK),
    USING INDEX ENABLE
);
